"""Tests for the translation catalogues.

These are not tests of the application: they check that every language it
claims to speak is complete, that the catalogues still match the strings in the
sources, and that the compiled ``.qm`` files were rebuilt from them.  They are
marked ``i18n`` so that ``make test`` can leave them out and ``make test-i18n``
can run them alone.

A language with a missing or half-finished catalogue fails here.  That is the
point: adding a string to the code without translating it is a broken
translation, not a warning.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path
from xml.etree import ElementTree

import pytest
from PyQt6.QtCore import QLocale, QTranslator

from masafi_simtwin.translations import (
    CATALOGUE_PREFIX,
    LANGUAGES,
    SOURCE_LANGUAGE,
    catalogue,
    directory,
)

pytestmark = pytest.mark.i18n

#: The package the strings are extracted from.
SOURCES = Path(__file__).resolve().parents[2] / 'src' / 'masafi_simtwin'


def messages(path: Path) -> dict[tuple[str, str, str], str | None]:
    """Read the messages of a catalogue.

    Parameters
    ----------
    path : pathlib.Path
        A ``.ts`` file.

    Returns
    -------
    dict
        The translation of every ``(context, source, disambiguation)`` message.
        The value is ``None`` when the message is untranslated or still marked
        unfinished.

    Notes
    -----
    The disambiguation belongs in the key.  One context may hold the same source
    twice — *System default* is offered by both the theme chooser and the
    language chooser — and keying on the source alone would let the translated
    one silently stand in for the untranslated one.
    """

    found: dict[tuple[str, str, str], str | None] = {}
    for context in ElementTree.parse(path).getroot().iter('context'):
        name = context.findtext('name', '')
        for message in context.iter('message'):
            key = (
                name,
                message.findtext('source', ''),
                message.findtext('comment', ''),
            )
            translation = message.find('translation')
            if translation is None or translation.get('type') or not translation.text:
                found[key] = None
            else:
                found[key] = translation.text
    return found


@pytest.fixture(scope='module')
def extracted(tmp_path_factory):
    """Extract the source strings again, into a catalogue of their own.

    Parameters
    ----------
    tmp_path_factory : pytest.TempPathFactory
        Factory for the temporary directory.

    Returns
    -------
    dict
        The messages ``pylupdate6`` finds in the sources as they are now.
    """

    pylupdate = Path(sys.executable).parent / 'pylupdate6'
    if not pylupdate.exists():
        pylupdate = Path(shutil.which('pylupdate6') or 'pylupdate6')
    target = tmp_path_factory.mktemp('translations') / f'{CATALOGUE_PREFIX}_xx.ts'
    subprocess.run(
        [str(pylupdate), '--no-obsolete', '--ts', str(target), str(SOURCES)],
        check=True,
        capture_output=True,
    )
    return messages(target)


@pytest.mark.parametrize('language', LANGUAGES)
def test_every_language_has_a_catalogue(language):
    """A language the application offers is a language with a ``.ts`` file."""

    assert catalogue(language, '.ts').exists()


@pytest.mark.parametrize('language', LANGUAGES)
def test_the_catalogue_covers_every_string_in_the_sources(language, extracted):
    """A string added to the code is missing here until `make ts` is run."""

    present = set(messages(catalogue(language, '.ts')))

    assert set(extracted) - present == set()


@pytest.mark.parametrize('language', LANGUAGES)
def test_the_catalogue_holds_nothing_the_sources_no_longer_say(language, extracted):
    """A string dropped from the code is dropped from the catalogues with it."""

    present = set(messages(catalogue(language, '.ts')))

    assert present - set(extracted) == set()


@pytest.mark.parametrize('language', LANGUAGES)
def test_every_message_is_translated(language):
    """Nothing is left empty or marked unfinished."""

    untranslated = [
        key for key, translation in messages(catalogue(language, '.ts')).items()
        if translation is None
    ]

    assert untranslated == []


def test_the_source_catalogue_repeats_the_source():
    """English is the source language, so its catalogue is the source itself.

    It is generated by ``tools/update_translations.py``; an entry that differs
    means the file was edited by hand.
    """

    differing = [
        source for (_context, source, _comment), translation
        in messages(catalogue(SOURCE_LANGUAGE, '.ts')).items()
        if translation != source
    ]

    assert differing == []


@pytest.mark.parametrize('language', LANGUAGES)
def test_the_catalogue_is_compiled(language):
    """The ``.qm`` the application loads is there and loads."""

    translator = QTranslator()

    assert translator.load(str(catalogue(language, '.qm')))


@pytest.mark.parametrize('language', LANGUAGES)
def test_the_compiled_catalogue_matches_its_source(language):
    """The ``.qm`` was built from the ``.ts`` as it stands, not an older one.

    The context and the source go in as bytes: ``QTranslator.translate`` takes
    a ``const char *``, which PyQt encodes as ASCII, and the source strings
    hold characters such as the ellipsis of *New Project…*.
    """

    translator = QTranslator()
    translator.load(str(catalogue(language, '.qm')))
    stale = [
        source
        for (context, source, _comment), translation
        in messages(catalogue(language, '.ts')).items()
        if translator.translate(context.encode(), source.encode()) != translation
    ]

    assert stale == []


@pytest.mark.parametrize('language', LANGUAGES)
def test_the_accelerators_of_the_menu_bar_stay_unique(language):
    """Two menu titles of one language never answer to the same key."""

    keys = [
        translation[translation.index('&') + 1].lower()
        for (context, source, _comment), translation
        in messages(catalogue(language, '.ts')).items()
        if context == 'MainWindow' and source.startswith('&') and translation
    ]

    assert len(keys) == len(set(keys))


@pytest.mark.parametrize('language', LANGUAGES)
def test_the_placeholders_survive_translation(language):
    """A translated string keeps the ``{0}`` the code fills in."""

    wrong = [
        source
        for (_context, source, _comment), translation
        in messages(catalogue(language, '.ts')).items()
        if translation and set(re.findall(r'{\d+}', source)) != set(re.findall(r'{\d+}', translation))
    ]

    assert wrong == []


def test_the_application_speaks_every_language(qapp):
    """Each catalogue can be installed on the running application.

    Parameters
    ----------
    qapp : masafi_simtwin.application.SimTwinApplication
        The application pytest-qt built.
    """

    try:
        for language in LANGUAGES:
            assert qapp.install_application_translator(QLocale(language))
            assert qapp.translate('MainWindow', 'Ready')
            qapp.remove_translators()
    finally:
        qapp.remove_translators()


def test_the_catalogues_are_the_only_thing_in_the_directory():
    """Nothing but the two catalogues of each language is shipped."""

    unexpected = [
        path.name
        for path in directory().iterdir()
        if path.suffix in {'.ts', '.qm'}
        and path.stem not in {f'{CATALOGUE_PREFIX}_{language}' for language in LANGUAGES}
    ]

    assert unexpected == []
