# Form implementation generated from reading ui file 'src/masafi_simtwin/dialogs/forms/about.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(420, 232)
        AboutDialog.setWindowTitle("About")
        AboutDialog.setModal(True)
        self.dialog_layout = QtWidgets.QVBoxLayout(AboutDialog)
        self.dialog_layout.setSpacing(16)
        self.dialog_layout.setObjectName("dialog_layout")
        self.header_layout = QtWidgets.QHBoxLayout()
        self.header_layout.setSpacing(16)
        self.header_layout.setObjectName("header_layout")
        self.logo_widget = QSvgWidget(parent=AboutDialog)
        self.logo_widget.setMinimumSize(QtCore.QSize(64, 64))
        self.logo_widget.setMaximumSize(QtCore.QSize(64, 64))
        self.logo_widget.setObjectName("logo_widget")
        self.header_layout.addWidget(self.logo_widget)
        self.identity_layout = QtWidgets.QVBoxLayout()
        self.identity_layout.setSpacing(2)
        self.identity_layout.setObjectName("identity_layout")
        self.name_label = QtWidgets.QLabel(parent=AboutDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.name_label.setFont(font)
        self.name_label.setText("MASAFI-SimTwin")
        self.name_label.setObjectName("name_label")
        self.identity_layout.addWidget(self.name_label)
        self.version_label = QtWidgets.QLabel(parent=AboutDialog)
        self.version_label.setText("")
        self.version_label.setObjectName("version_label")
        self.identity_layout.addWidget(self.version_label)
        spacerItem = QtWidgets.QSpacerItem(0, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.identity_layout.addItem(spacerItem)
        self.summary_label = QtWidgets.QLabel(parent=AboutDialog)
        self.summary_label.setWordWrap(True)
        self.summary_label.setObjectName("summary_label")
        self.identity_layout.addWidget(self.summary_label)
        self.header_layout.addLayout(self.identity_layout)
        self.dialog_layout.addLayout(self.header_layout)
        self.separator = QtWidgets.QFrame(parent=AboutDialog)
        self.separator.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.separator.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.separator.setObjectName("separator")
        self.dialog_layout.addWidget(self.separator)
        self.licence_label = QtWidgets.QLabel(parent=AboutDialog)
        self.licence_label.setWordWrap(True)
        self.licence_label.setObjectName("licence_label")
        self.dialog_layout.addWidget(self.licence_label)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.dialog_layout.addItem(spacerItem1)
        self.button_box = QtWidgets.QDialogButtonBox(parent=AboutDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.button_box.setObjectName("button_box")
        self.dialog_layout.addWidget(self.button_box)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        self.summary_label.setText(_translate("AboutDialog", "Graphical frontend for the MASAFI simulation libraries."))
        self.licence_label.setText(_translate("AboutDialog", "Released under the GNU General Public License, version 3 or later."))
from PyQt6.QtSvgWidgets import QSvgWidget
