# Form implementation generated from reading ui file 'src/masafi_simtwin/dialogs/forms/arc.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ArcDialog(object):
    def setupUi(self, ArcDialog):
        ArcDialog.setObjectName("ArcDialog")
        ArcDialog.resize(320, 150)
        ArcDialog.setModal(True)
        self.dialog_layout = QtWidgets.QVBoxLayout(ArcDialog)
        self.dialog_layout.setSpacing(12)
        self.dialog_layout.setObjectName("dialog_layout")
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setHorizontalSpacing(12)
        self.form_layout.setVerticalSpacing(8)
        self.form_layout.setObjectName("form_layout")
        self.weight_label = QtWidgets.QLabel(parent=ArcDialog)
        self.weight_label.setObjectName("weight_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.weight_label)
        self.weight_spin = QtWidgets.QSpinBox(parent=ArcDialog)
        self.weight_spin.setMinimum(1)
        self.weight_spin.setMaximum(999999)
        self.weight_spin.setProperty("value", 1)
        self.weight_spin.setObjectName("weight_spin")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.weight_spin)
        self.dialog_layout.addLayout(self.form_layout)
        self.hint_label = QtWidgets.QLabel(parent=ArcDialog)
        self.hint_label.setWordWrap(True)
        self.hint_label.setObjectName("hint_label")
        self.dialog_layout.addWidget(self.hint_label)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.dialog_layout.addItem(spacerItem)
        self.button_box = QtWidgets.QDialogButtonBox(parent=ArcDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.dialog_layout.addWidget(self.button_box)
        self.weight_label.setBuddy(self.weight_spin)

        self.retranslateUi(ArcDialog)
        QtCore.QMetaObject.connectSlotsByName(ArcDialog)

    def retranslateUi(self, ArcDialog):
        _translate = QtCore.QCoreApplication.translate
        ArcDialog.setWindowTitle(_translate("ArcDialog", "Arc"))
        self.weight_label.setText(_translate("ArcDialog", "Weight"))
        self.hint_label.setText(_translate("ArcDialog", "How many tokens the arc carries. A weight of one is not drawn."))
