# Form implementation generated from reading ui file 'src/masafi_simtwin/dialogs/forms/new_project.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewProjectDialog(object):
    def setupUi(self, NewProjectDialog):
        NewProjectDialog.setObjectName("NewProjectDialog")
        NewProjectDialog.resize(560, 220)
        NewProjectDialog.setModal(True)
        self.dialog_layout = QtWidgets.QVBoxLayout(NewProjectDialog)
        self.dialog_layout.setSpacing(12)
        self.dialog_layout.setObjectName("dialog_layout")
        self.fields_layout = QtWidgets.QGridLayout()
        self.fields_layout.setHorizontalSpacing(12)
        self.fields_layout.setVerticalSpacing(8)
        self.fields_layout.setObjectName("fields_layout")
        self.name_label = QtWidgets.QLabel(parent=NewProjectDialog)
        self.name_label.setObjectName("name_label")
        self.fields_layout.addWidget(self.name_label, 0, 0, 1, 1)
        self.name_edit = QtWidgets.QLineEdit(parent=NewProjectDialog)
        self.name_edit.setObjectName("name_edit")
        self.fields_layout.addWidget(self.name_edit, 0, 1, 1, 2)
        self.location_label = QtWidgets.QLabel(parent=NewProjectDialog)
        self.location_label.setObjectName("location_label")
        self.fields_layout.addWidget(self.location_label, 1, 0, 1, 1)
        self.location_edit = QtWidgets.QLineEdit(parent=NewProjectDialog)
        self.location_edit.setObjectName("location_edit")
        self.fields_layout.addWidget(self.location_edit, 1, 1, 1, 1)
        self.browse_button = QtWidgets.QPushButton(parent=NewProjectDialog)
        self.browse_button.setAutoDefault(False)
        self.browse_button.setObjectName("browse_button")
        self.fields_layout.addWidget(self.browse_button, 1, 2, 1, 1)
        self.dialog_layout.addLayout(self.fields_layout)
        self.path_label = QtWidgets.QLabel(parent=NewProjectDialog)
        self.path_label.setProperty("placeholder", True)
        self.path_label.setWordWrap(True)
        self.path_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.path_label.setText("")
        self.path_label.setObjectName("path_label")
        self.dialog_layout.addWidget(self.path_label)
        self.message_label = QtWidgets.QLabel(parent=NewProjectDialog)
        self.message_label.setProperty("error", True)
        self.message_label.setWordWrap(True)
        self.message_label.setText("")
        self.message_label.setObjectName("message_label")
        self.dialog_layout.addWidget(self.message_label)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.dialog_layout.addItem(spacerItem)
        self.button_box = QtWidgets.QDialogButtonBox(parent=NewProjectDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.dialog_layout.addWidget(self.button_box)

        self.retranslateUi(NewProjectDialog)
        QtCore.QMetaObject.connectSlotsByName(NewProjectDialog)

    def retranslateUi(self, NewProjectDialog):
        _translate = QtCore.QCoreApplication.translate
        NewProjectDialog.setWindowTitle(_translate("NewProjectDialog", "New Project"))
        self.name_label.setText(_translate("NewProjectDialog", "Name:"))
        self.name_edit.setPlaceholderText(_translate("NewProjectDialog", "Untitled"))
        self.location_label.setText(_translate("NewProjectDialog", "Location:"))
        self.browse_button.setText(_translate("NewProjectDialog", "Browse…"))
